### PR TITLE
Deploy to Github Pages

### PR DESCRIPTION
**Pull request by Isaac-Flath**
This PR creates a quarto website for the apl-study repo with a custom font that works with APL glyphs.  This is using Jeremy's latest APL notebook as of now.  cc @jph00 

See page for website:  https://isaac-flath.github.io/apl-study/

You will need to go to settings -> pages -> and deploy to github pages using the docs folder after PR is accepted.

As @hamelsmu  is going to be working on making nbprocess work with other languages I thought getting particular challenges I ran into out there quickly would be helpful to be aware of.  

Stuff maybe nbprocess or Quarto developments can help with:
- ~~I believe (please test) that in order to properly build the site you will have to install the APL font on your machine [SAX2.ttf](https://github.com/Isaac-Flath/apl-study/blob/master/apl/SAX2.ttf).  Ideally we could reference the ttf file and have `nbprocess` install automatically if needed rather than a separate step.  This is specified in the `_quarto.yml` file~~ Figured this out via `styles.css` file
- ~~Quarto flags do not work well because `#|` is not seen as a comment in APL and other languages~~ Quarto Fixed this.

Related to APL Font:
- We used a specific font for APL (SAX2) as APL glyphs are unusual and don't work well with many fonts.
- ~~I changed the default theme in the `_quarto.yml` file.  When using the SAX2 font - headers do not stand out and it makes the posts hard to read.  I chose a similar theme where headers are a different color for readability.~~ Used styles.css instead
- ~~The APL font doesn't look great with code blocks - future improvement could be to customize a theme to make code blocks look better~~ I added minimal background styling to address

### CODE REVIEW

**Comment by Isaac-Flath** [comment]
I was able to improve a lot of the font issues that was having by setting only the code font to the APL compliant font as opposed to the full site font.  Didn't know that was an option, but is much better aesthetically!

That allowed the default theme headers to be clear and look better, so I reverted to the default theme with a minimal code background color.

**Comment by jph00** [comment]
I don't see any webfont embedding here - did I miss it, or is it not there? If it's not, then folks would need the font installed locally.

I think we should use CI to build the docs. People cloning the repo aren't going to want to have the whole Web site too!

**Comment by Isaac-Flath** [comment]
Web font should be there now and is working after the last commit - I didn't know what webfont meant and assumed it just meant a font downloaded from the web.  I used the styles.css for this since I do not think there is a Quarto configuration for this.

Working on CI to build the docs and hope to complete soon.  I have not used github actions before so it may take a couple of days, but I do want to figure this out!

**Comment by Isaac-Flath** [comment]
@jph00 Done!

- Web font is implemented via [styles.css](https://github.com/Isaac-Flath/apl-study/blob/master/apl/styles.css), putting it on code cells only.
- CI builds docs now via [deploy.yaml](https://github.com/Isaac-Flath/apl-study/blob/master/.github/workflows/deploy.yaml)

**Comment by jph00** [comment]
That was quick!

**Comment by Isaac-Flath** [comment]
Luckily I had good reference material due to fastkaggle and nbprocess :)

As a reminder you will have to go to settings -> Pages -> and set to gh-pages branch for the deploy.

**Pull request merged**
